### PR TITLE
Appended web2 dictionary on top of existing library

### PR DESCRIPTION
**Pull request by fresh4**
## Contribution notes
* Added `web2.txt`, which is a new line separated list of nearly 236,000 words.
* In addition to the existing sets, which uses [this original dictionary](https://svnweb.freebsd.org/csrg/share/dict/) as a source, I import the `web2.txt` contents into a set `web2_words_set`, and also created a `web2_lower_set` which is the same thing but parsed to lowercase.

I didn't want to replace the old sets just yet. While the new set is far more exhaustive, it also doesn't contain any special characters at all, which makes the alpha set distinctions redundant. So I've just kept both for now, with the web2 option having more words.

### CODE REVIEW

**Comment by mwiens91** [comment]
I might change the structure of this. See comments in #2.

**Comment by mwiens91** [comment]
In the meantime, I'll push your changes to a new version on PyPI.

**Comment by TaylorSMarks** [comment]
This second set is also imperfect... neither contains "cats" or "boxes". The new one contains "dogs", but it lacks "fridge" (which the old one had).

I'm literally just throwing darts to see what is/isn't in each list...

**Comment by fresh4** [comment]
@TaylorSMarks That is pretty odd that those pretty basic words are missing, and probably tons more. No set's gonna be exhaustive, but the best we can do is combine as many word sets as possible, maybe into one master set with redundancies removed to reduce inflating the package size too much.

**Comment by mwiens91** [comment]
@TaylorSMarks I've rewritten this package so we can combine word lists from multiple sources. In theory, we can just add more word lists to combine together to get higher word coverage. Combining the "web2" and "gcide" word lists that we have right now, "fridge" is included, and so is "cat, "dog", "box"... but neither word list contains the plural forms of these.

I don't know where to find good word lists that have high coverage :(

**Pull request merged**
